name: distributed_dart
version: 0.0.1
author: Brian Astrup Mikkelsen and Jacob Bang
description: Distributed Dart
homepage: https://github.com/SW108F13-AAU/distributed_dart
dev_dependencies:
  unittest: any
  crypto: any
